// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAid8MwdL2LJ5J-B1rdn1eKQ1WMctO7Hl8',
    appId: '1:316111098749:web:87e4616780eb43fde57214',
    messagingSenderId: '316111098749',
    projectId: 'prisma-73071',
    authDomain: 'prisma-73071.firebaseapp.com',
    storageBucket: 'prisma-73071.appspot.com',
    measurementId: 'G-M567DY6PZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATe0yVQk3lmFyT4X964Maaix0gpqLu_TA',
    appId: '1:316111098749:android:a55ece8c28a7b41be57214',
    messagingSenderId: '316111098749',
    projectId: 'prisma-73071',
    storageBucket: 'prisma-73071.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXhDF7KnkG_Tzq6k_dynfZpVfNIR0QPg0',
    appId: '1:316111098749:ios:1957fdc7ca79e7d7e57214',
    messagingSenderId: '316111098749',
    projectId: 'prisma-73071',
    storageBucket: 'prisma-73071.appspot.com',
    iosBundleId: 'com.example.prisma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXhDF7KnkG_Tzq6k_dynfZpVfNIR0QPg0',
    appId: '1:316111098749:ios:1957fdc7ca79e7d7e57214',
    messagingSenderId: '316111098749',
    projectId: 'prisma-73071',
    storageBucket: 'prisma-73071.appspot.com',
    iosBundleId: 'com.example.prisma',
  );
}
